# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Storie di Terra
lang: it-IT
email: debbie@storiediterra.it
description: >- # this means to ignore newlines until "baseurl:"
  Storie di Terra è un podcast itinerante che racconta personaggi che producono vino in territori densi di storia.
  Abbiamo sorseggiato e ascoltato, abbiamo scoperto sia racconti che affondano le radici nel Medioevo che aneddoti contemporanei e avvolti dall’ebrezza ci siamo lasciati conquistare dal mistero di ogni territorio.
  Ci ha guidato la passione per il vino, per le storie, per i sogni.
  Avete voglia di seguirci?
  Andiamo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://storiediterra.it" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
